openapi: 3.0.0
info:
  title: Education Platform API
  version: 1.0.0
  description: API for managing courses and quizzes in an educational platform

paths:
  /api/courses:
    post:
      summary: Create a new course
      description: This endpoint creates a new course.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'  # Reference to the Course schema
      responses:
        '201':
          description: Course created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'  # Referencing the Course schema for the response
        '400':
          description: Bad request

    get:
      summary: Retrieve a list of all courses
      description: Get all courses from the system
      responses:
        '200':
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'  # Course schema for the response
        '400':
          description: Bad request

  /api/courses/{id}:
    get:
      summary: Get a specific course
      description: Retrieve details of a specific course by its ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the course to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Details of the specific course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'  # Course schema for the response
        '404':
          description: Course not found
        '400':
          description: Invalid ID format

    put:
      summary: Update a course
      description: Update an existing course by its ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the course to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'  # Course schema for the request
      responses:
        '200':
          description: Successfully updated the course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '404':
          description: Course not found
        '400':
          description: Bad request

    delete:
      summary: Delete a course
      description: Delete a course by its ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the course to delete
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the course
        '404':
          description: Course not found
        '400':
          description: Invalid ID format

  /api/courses/{courseId}/quizzes:
    post:
      summary: Create a quiz for a specific course
      parameters:
        - in: path
          name: courseId
          required: true
          description: ID of the course to create the quiz for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'  # Referencing the Quiz schema
      responses:
        '201':
          description: Quiz created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'  # Quiz schema for the response
        '404':
          description: Course not found
        '400':
          description: Bad request

    get:
      summary: Get all quizzes for a specific course
      parameters:
        - in: path
          name: courseId
          required: true
          description: ID of the course to fetch quizzes for
          schema:
            type: string
      responses:
        '200':
          description: List of quizzes for the course
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
        '404':
          description: Course not found
        '400':
          description: Bad request

  /api/quizzes/{id}:
    get:
      summary: Get a specific quiz by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the quiz to fetch
          schema:
            type: string
      responses:
        '200':
          description: Quiz data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz not found
        '400':
          description: Bad request

    put:
      summary: Update a specific quiz by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the quiz to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'  # Quiz schema for the request
      responses:
        '200':
          description: Quiz updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz not found
        '400':
          description: Bad request

    delete:
      summary: Delete a specific quiz by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the quiz to delete
          schema:
            type: string
      responses:
        '200':
          description: Quiz deleted successfully
        '404':
          description: Quiz not found
        '400':
          description: Bad request

components:
  schemas:
    Course:
      type: object
      required:
        - title
        - description
        - duration
        - instructorName
        - language
        - level
      properties:
        title:
          type: string
          description: Title of the course
        description:
          type: string
          description: Description of the course
        duration:
          type: integer
          description: Duration of the course in hours
        instructorName:
          type: string
          description: Instructor's name
        language:
          type: string
          description: Language of instruction
        level:
          type: string
          description: Level of the course (beginner, intermediate, advanced)

    Quiz:
      type: object
      required:
        - question
        - options
        - correctAnswer
      properties:
        question:
          type: string
          description: The question for the quiz
        options:
          type: array
          items:
            type: string
          description: Array of options for the quiz question
        correctAnswer:
          type: string
          description: The correct answer for the quiz question
